import './globals.css'
import type { Metadata } from 'next'
import { Navbar } from '@/components'
import { Inter } from 'next/font/google'
import { Footer } from '@/components/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col justify-between h-screen max-2xl:max-w-[1500px]'>
          <div>
            <Navbar />
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
